language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: 39MDkPeIYdEB/BVbd6T5thXoe4pilRIk8Q3XVQYIN2ViNeUCU4bTv2AMhk7Vjly2qyWdzbXTLTk7srJ9j0dHh52RTnbU2d9NXnb6andS+v9gzWkDFf/efyIfSKWvtPwTcs62bST5wEo0e6h/Mf8llD3AANXAZ3CY+gV8rEw2+AIp9keQJqq+b/LVMYmL4C8cSxPyibELw7nKYliCg8BHQph0KwO4X0omt6NRNVbd4jEjPpy8PjDabH17iNMd5QbFlsSYhsLnG8bfCAKGUOQoTMChY9fb6lQi8/FcLlQLRC0UjbZMP4Kdf9SeWEzjIT7tE4QRa8k4KcIRjpkFZiOa/CgQiXX8gRs40G90g5rbCsu3t4LgBbfUVKJrE0/VIJCkKu29ZHjEv93TQ+zRiQBvoK3uHRQ5+r4HL3xptXP5MOnmWD7zq7RGsZY/fW+ttK9GQ7p/Qz0P1whoQvG0Awp+ZG6MaosqPi5/G6OIKJ09Xpk4HAqryJQ0+w1n2yBDPA79enpjgTX7NfB+lSo3JUHxaGS+iH/pWB2YjAHoJ+LJoL0UljbxVQSxsEAkcPJnauwzuWQH/IHzLlEfWro6R8ALOAyqbW3CsxNHlEsF5YMjYPvR9NU1dINQErVTgBxfd1ienPxhuTTDdF0MeAvsrSGr6XvAXcf7yFU8BRqAOXhWXRQ=
  app: node-exp-tracker
  on:
    repo: rrogerthat/exp-tracker-Node-Capstone-App
